% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Analysis Of Space Missions},
  pdfauthor={Namrata Joshi},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Analysis Of Space Missions}
\author{Namrata Joshi}
\date{2023-08-07}

\begin{document}
\maketitle

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

This is my first R project that I completed to analyze the \textbf{space
missions data from 1957 to August 2022}.

This interesting dataset is obtained from \textbf{Maven Analytics} data
playground which contains details on the location, date, and result of
the launch, the company responsible, and the name, price, and status of
the rocket used for the mission.

Here, I have used R to \textbf{explore}, \textbf{clean} and
\textbf{transform} the data extracting useful information to further
\textbf{analyze} and \textbf{visualize} it to find trends in the space
missions from 1957 to 2022.

\hypertarget{questions-to-explore}{%
\subsection{Questions to explore}\label{questions-to-explore}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Which countries have had the most successful space missions? Has it
  always been that way?
\item
  How have rocket launches trended across time? Has mission success rate
  increased?
\item
  Which rocket has been used for the most space missions? Is it still
  active?
\end{enumerate}

\hypertarget{set-up}{%
\section{Set up}\label{set-up}}

\hypertarget{loading-required-libraries}{%
\subsubsection{Loading Required
libraries}\label{loading-required-libraries}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{knitr}\SpecialCharTok{::}\NormalTok{opts\_chunk}\SpecialCharTok{$}\FunctionTok{set}\NormalTok{(}\AttributeTok{eval =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{warning =} \ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'tidyverse' was built under R version 4.3.1
\end{verbatim}

\begin{verbatim}
## -- Attaching core tidyverse packages ------------------------ tidyverse 2.0.0 --
## v dplyr     1.1.2     v readr     2.1.4
## v forcats   1.0.0     v stringr   1.5.0
## v ggplot2   3.4.2     v tibble    3.2.1
## v lubridate 1.9.2     v tidyr     1.3.0
## v purrr     1.0.1     
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## i Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
\end{verbatim}

\hypertarget{loading-data}{%
\subsubsection{Loading Data}\label{loading-data}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\FunctionTok{file.choose}\NormalTok{(),}\AttributeTok{header =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{data-exploration}{%
\section{Data Exploration}\label{data-exploration}}

In this phase, I will explore the data looking at the structure and
summary of the data, identifying variable names, types and presence of
any duplicate data.

\hypertarget{looking-at-the-structure-of-the-data}{%
\subsubsection{Looking at the structure of the
data}\label{looking-at-the-structure-of-the-data}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{glimpse}\NormalTok{(space\_missions)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 4,630
## Columns: 9
## $ Company       <chr> "RVSN USSR", "RVSN USSR", "US Navy", "AMBA", "US Navy", ~
## $ Location      <chr> "Site 1/5, Baikonur Cosmodrome, Kazakhstan", "Site 1/5, ~
## $ Date          <chr> "1957-10-04", "1957-11-03", "1957-12-06", "1958-02-01", ~
## $ Time          <chr> "19:28:00", "02:30:00", "16:44:00", "03:48:00", "07:33:0~
## $ Rocket        <chr> "Sputnik 8K71PS", "Sputnik 8K71PS", "Vanguard", "Juno I"~
## $ Mission       <chr> "Sputnik-1", "Sputnik-2", "Vanguard TV3", "Explorer 1", ~
## $ RocketStatus  <chr> "Retired", "Retired", "Retired", "Retired", "Retired", "~
## $ Price         <chr> "", "", "", "", "", "", "", "", "", "", "", "", "", "", ~
## $ MissionStatus <chr> "Success", "Success", "Failure", "Success", "Failure", "~
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(space\_missions)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Company                                  Location       Date     Time
## 1 RVSN USSR Site 1/5, Baikonur Cosmodrome, Kazakhstan 1957-10-04 19:28:00
## 2 RVSN USSR Site 1/5, Baikonur Cosmodrome, Kazakhstan 1957-11-03 02:30:00
## 3   US Navy  LC-18A, Cape Canaveral AFS, Florida, USA 1957-12-06 16:44:00
## 4      AMBA  LC-26A, Cape Canaveral AFS, Florida, USA 1958-02-01 03:48:00
## 5   US Navy  LC-18A, Cape Canaveral AFS, Florida, USA 1958-02-05 07:33:00
## 6      AMBA  LC-26A, Cape Canaveral AFS, Florida, USA 1958-03-05 18:27:00
##           Rocket        Mission RocketStatus Price MissionStatus
## 1 Sputnik 8K71PS      Sputnik-1      Retired             Success
## 2 Sputnik 8K71PS      Sputnik-2      Retired             Success
## 3       Vanguard   Vanguard TV3      Retired             Failure
## 4         Juno I     Explorer 1      Retired             Success
## 5       Vanguard Vanguard TV3BU      Retired             Failure
## 6         Juno I     Explorer 2      Retired             Failure
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tail}\NormalTok{(space\_missions)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        Company                                        Location       Date
## 4625    SpaceX        SLC-40, Cape Canaveral SFS, Florida, USA 2022-07-17
## 4626    SpaceX         SLC-4E, Vandenberg SFB, California, USA 2022-07-22
## 4627      CASC LC-101, Wenchang Satellite Launch Center, China 2022-07-24
## 4628    SpaceX      LC-39A, Kennedy Space Center, Florida, USA 2022-07-24
## 4629 CAS Space          Jiuquan Satellite Launch Center, China 2022-07-27
## 4630      CASC    LC-3, Xichang Satellite Launch Center, China 2022-07-29
##          Time           Rocket             Mission RocketStatus Price
## 4625 14:20:00 Falcon 9 Block 5 Starlink Group 4-22       Active    67
## 4626 17:39:00 Falcon 9 Block 5  Starlink Group 3-2       Active    67
## 4627 06:22:00    Long March 5B             Wentian       Active      
## 4628 13:38:00 Falcon 9 Block 5 Starlink Group 4-25       Active    67
## 4629 04:12:00       Zhongke-1A         Demo Flight       Active      
## 4630 13:28:00    Long March 2D  Yaogan 35 Group 03       Active 29.75
##      MissionStatus
## 4625       Success
## 4626       Success
## 4627       Success
## 4628       Success
## 4629       Success
## 4630       Success
\end{verbatim}

\hypertarget{identifying-duplicate-data}{%
\subsubsection{Identifying duplicate
data}\label{identifying-duplicate-data}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions[}\FunctionTok{duplicated}\NormalTok{(space\_missions), ]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Company                                                  Location
## 3532    CASC Site 9401 (SLS-2), Jiuquan Satellite Launch Center, China
##            Date     Time        Rocket                    Mission RocketStatus
## 3532 2008-11-05 00:15:00 Long March 2D Shiyan-3 & Chuangxin-1(02)       Active
##      Price MissionStatus
## 3532 29.75       Success
\end{verbatim}

There is one duplicate row as seen from the above code

\hypertarget{summary-of-data}{%
\subsubsection{Summary of data}\label{summary-of-data}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(space\_missions)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Company            Location             Date               Time          
##  Length:4630        Length:4630        Length:4630        Length:4630       
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##     Rocket            Mission          RocketStatus          Price          
##  Length:4630        Length:4630        Length:4630        Length:4630       
##  Class :character   Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character   Mode  :character  
##  MissionStatus     
##  Length:4630       
##  Class :character  
##  Mode  :character
\end{verbatim}

\hypertarget{data-cleaning}{%
\section{Data Cleaning}\label{data-cleaning}}

In this phase, I will process the data to remove duplicate rows,
identify and replace blank values with NA values, identify the number of
NA values, change column names for readability and change few of the
variable types for consistency and accuracy.

\hypertarget{creating-a-copy-of-the-exisiting-dataframe-to-facilitate-cleaning}{%
\subsubsection{Creating a copy of the exisiting dataframe to facilitate
cleaning}\label{creating-a-copy-of-the-exisiting-dataframe-to-facilitate-cleaning}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_cleaned }\OtherTok{\textless{}{-}}\NormalTok{ space\_missions}
\end{Highlighting}
\end{Shaded}

\hypertarget{replacing-blank-values-in-dataset-with-na-values}{%
\subsubsection{Replacing blank values in dataset with ``NA''
values}\label{replacing-blank-values-in-dataset-with-na-values}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_cleaned[space\_missions\_cleaned }\SpecialCharTok{==} \StringTok{""}\NormalTok{] }\OtherTok{\textless{}{-}} \ConstantTok{NA}
\end{Highlighting}
\end{Shaded}

\hypertarget{finding-out-the-number-of-na-values-in-the-variables}{%
\subsubsection{Finding out the number of ``NA'' values in the
variables}\label{finding-out-the-number-of-na-values-in-the-variables}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(space\_missions\_cleaned))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3492
\end{verbatim}

\hypertarget{finding-out-the-number-of-na-values-in-each-variable}{%
\subsubsection{Finding out the number of ``NA'' values in each
variable}\label{finding-out-the-number-of-na-values-in-each-variable}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(space\_missions\_cleaned}\SpecialCharTok{$}\NormalTok{Company))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(space\_missions\_cleaned}\SpecialCharTok{$}\NormalTok{Location))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(space\_missions\_cleaned}\SpecialCharTok{$}\NormalTok{Date))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(space\_missions\_cleaned}\SpecialCharTok{$}\NormalTok{Time))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 127
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(space\_missions\_cleaned}\SpecialCharTok{$}\NormalTok{Rocket))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(space\_missions\_cleaned}\SpecialCharTok{$}\NormalTok{Mission))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(space\_missions\_cleaned}\SpecialCharTok{$}\NormalTok{RocketStatus))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(space\_missions\_cleaned}\SpecialCharTok{$}\NormalTok{Price))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3365
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sum}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(space\_missions\_cleaned}\SpecialCharTok{$}\NormalTok{MissionStatus))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

We can see that ``Price'' Variable has the maximum number of NA values-
3365 out of 4630 rows and hence we don't have enough data on Price to
use it for our analysis to identify trends.

\hypertarget{changing-column-names-from-camel-case-to-lower-case}{%
\subsubsection{Changing column names from camel case to lower
case}\label{changing-column-names-from-camel-case-to-lower-case}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colnames}\NormalTok{(space\_missions\_cleaned) }\OtherTok{\textless{}{-}} \FunctionTok{tolower}\NormalTok{(}\FunctionTok{colnames}\NormalTok{(space\_missions\_cleaned))}
\end{Highlighting}
\end{Shaded}

\hypertarget{adding-underscores-in-few-of-the-columns-for-better-visibility}{%
\subsubsection{Adding underscores in few of the columns for better
visibility}\label{adding-underscores-in-few-of-the-columns-for-better-visibility}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colnames}\NormalTok{(space\_missions\_cleaned) }\OtherTok{\textless{}{-}} \FunctionTok{gsub}\NormalTok{(}\StringTok{"rocketstatus"}\NormalTok{,}\StringTok{"rocket\_status"}\NormalTok{,}
                                         \FunctionTok{gsub}\NormalTok{(}\StringTok{"missionstatus"}\NormalTok{,}\StringTok{"mission\_status"}\NormalTok{,}
                                              \FunctionTok{colnames}\NormalTok{(space\_missions\_cleaned)))}
\end{Highlighting}
\end{Shaded}

\hypertarget{changing-the-date-rocket-status-and-mission-status-variables-format}{%
\subsubsection{Changing the date, rocket status and mission status
variables
format}\label{changing-the-date-rocket-status-and-mission-status-variables-format}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_cleaned }\OtherTok{\textless{}{-}}\NormalTok{ space\_missions\_cleaned }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{date =} \FunctionTok{as\_date}\NormalTok{(date)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{rocket\_status=} \FunctionTok{as.factor}\NormalTok{(rocket\_status)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{mission\_status=} \FunctionTok{as.factor}\NormalTok{(mission\_status)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{glimpse}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Rows: 4,630
## Columns: 9
## $ company        <chr> "RVSN USSR", "RVSN USSR", "US Navy", "AMBA", "US Navy",~
## $ location       <chr> "Site 1/5, Baikonur Cosmodrome, Kazakhstan", "Site 1/5,~
## $ date           <date> 1957-10-04, 1957-11-03, 1957-12-06, 1958-02-01, 1958-0~
## $ time           <chr> "19:28:00", "02:30:00", "16:44:00", "03:48:00", "07:33:~
## $ rocket         <chr> "Sputnik 8K71PS", "Sputnik 8K71PS", "Vanguard", "Juno I~
## $ mission        <chr> "Sputnik-1", "Sputnik-2", "Vanguard TV3", "Explorer 1",~
## $ rocket_status  <fct> Retired, Retired, Retired, Retired, Retired, Retired, R~
## $ price          <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,~
## $ mission_status <fct> Success, Success, Failure, Success, Failure, Failure, S~
\end{verbatim}

We can see that rocket status and mission status are now changed to
factor format and date to a date format.

\hypertarget{creating-levels-for-the-rocket-status-and-mission-status}{%
\subsubsection{Creating levels for the rocket status and mission
status}\label{creating-levels-for-the-rocket-status-and-mission-status}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{levels}\NormalTok{(space\_missions\_cleaned}\SpecialCharTok{$}\NormalTok{rocket\_status)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Active"  "Retired"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{levels}\NormalTok{(space\_missions\_cleaned}\SpecialCharTok{$}\NormalTok{mission\_status)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Failure"           "Partial Failure"   "Prelaunch Failure"
## [4] "Success"
\end{verbatim}

\hypertarget{looking-at-the-summary-of-the-data-after-the-changes}{%
\subsubsection{Looking at the summary of the data after the
changes}\label{looking-at-the-summary-of-the-data-after-the-changes}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(space\_missions\_cleaned)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    company            location              date                time          
##  Length:4630        Length:4630        Min.   :1957-10-04   Length:4630       
##  Class :character   Class :character   1st Qu.:1973-02-18   Class :character  
##  Mode  :character   Mode  :character   Median :1987-03-08   Mode  :character  
##                                        Mean   :1990-02-19                     
##                                        3rd Qu.:2007-09-25                     
##                                        Max.   :2022-07-29                     
##     rocket            mission          rocket_status     price          
##  Length:4630        Length:4630        Active :1010   Length:4630       
##  Class :character   Class :character   Retired:3620   Class :character  
##  Mode  :character   Mode  :character                  Mode  :character  
##                                                                         
##                                                                         
##                                                                         
##            mission_status
##  Failure          : 357  
##  Partial Failure  : 107  
##  Prelaunch Failure:   4  
##  Success          :4162  
##                          
## 
\end{verbatim}

\hypertarget{data-tranformation}{%
\section{Data Tranformation}\label{data-tranformation}}

In this phase, I will make changes to the data for further processing by
adding new columns, finding and replacing few of the values to
appropriate values for the location to maintain consistency and
accuracy.

\hypertarget{creating-a-copy-of-the-cleaned-dataset-for-further-processing}{%
\subsubsection{Creating a copy of the cleaned dataset for further
processing}\label{creating-a-copy-of-the-cleaned-dataset-for-further-processing}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\OtherTok{\textless{}{-}}\NormalTok{ space\_missions\_cleaned}
\end{Highlighting}
\end{Shaded}

\hypertarget{extracting-country-from-the-location}{%
\subsubsection{Extracting country from the
location}\label{extracting-country-from-the-location}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\OtherTok{\textless{}{-}}\NormalTok{ space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{country =} \FunctionTok{word}\NormalTok{(location, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{extracting-year-from-the-date}{%
\subsubsection{Extracting year from the
date}\label{extracting-year-from-the-date}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\OtherTok{\textless{}{-}}\NormalTok{ space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{year =} \FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{format}\NormalTok{(date, }\StringTok{"\%Y"}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\hypertarget{looking-at-unique-countries}{%
\subsubsection{Looking at unique
countries}\label{looking-at-unique-countries}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(space\_missions\_transformed}\SpecialCharTok{$}\NormalTok{country)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "Kazakhstan" "USA"        "Russia"     "France"     "Japan"     
##  [6] "Kenya"      "Australia"  "China"      "India"      "Israel"    
## [11] "Canaria"    "Brazil"     "Sea"        "Korea"      "Ocean"     
## [16] "Iran"       "Facility"   "Zealand"    "Mexico"     "Site"
\end{verbatim}

\hypertarget{counting-the-number-of-missions-per-country}{%
\subsubsection{Counting the number of missions per
country}\label{counting-the-number-of-missions-per-country}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{count}\NormalTok{(country, }\AttributeTok{sort =}\NormalTok{T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       country    n
## 1         USA 1467
## 2      Russia 1416
## 3  Kazakhstan  719
## 4       China  365
## 5      France  318
## 6       Japan  130
## 7       India   82
## 8       Ocean   36
## 9     Zealand   28
## 10       Iran   16
## 11     Israel   11
## 12      Korea   10
## 13      Kenya    9
## 14  Australia    6
## 15        Sea    6
## 16     Mexico    4
## 17     Brazil    3
## 18    Canaria    2
## 19   Facility    1
## 20       Site    1
\end{verbatim}

\hypertarget{extracting-the-locations-without-the-proper-country-name}{%
\subsubsection{Extracting the locations without the proper country
name}\label{extracting-the-locations-without-the-proper-country-name}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{select}\NormalTok{(country, location)}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(country }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Ocean"}\NormalTok{, }\StringTok{"Sea"}\NormalTok{, }\StringTok{"Canaria"}\NormalTok{, }\StringTok{"Facility"}\NormalTok{, }\StringTok{"Site"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{View}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\hypertarget{renaming-country-names-based-on-the-other-location-information}{%
\subsubsection{Renaming country names based on the other location
information}\label{renaming-country-names-based-on-the-other-location-information}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\OtherTok{\textless{}{-}}
\NormalTok{  space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{country =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      location }\SpecialCharTok{==}\StringTok{"K{-}407 Submarine, Barents Sea Launch Area, Barents Sea"}\SpecialCharTok{|}
        \CommentTok{\# OR}
\NormalTok{        location }\SpecialCharTok{==} \StringTok{"K{-}496 Submarine, Barents Sea Launch Area, Barents Sea"}\SpecialCharTok{|}
        \CommentTok{\# OR}
\NormalTok{        location }\SpecialCharTok{==}\StringTok{"K{-}84 Submarine, Barents Sea Launch Area, Barents Sea"} \SpecialCharTok{\textasciitilde{}} \StringTok{"Barents Sea"}\NormalTok{,}
\NormalTok{      location }\SpecialCharTok{==} \StringTok{"LP Odyssey, Kiritimati Launch Area, Pacific Ocean"} \SpecialCharTok{\textasciitilde{}} \StringTok{"Pacific Ocean"}\NormalTok{,}
\NormalTok{      location }\SpecialCharTok{==} \StringTok{"LP{-}41, Kauai, Pacific Missile Range Facility"} \SpecialCharTok{\textasciitilde{}} \StringTok{"Range Facility"}\NormalTok{,}
\NormalTok{      location }\SpecialCharTok{==} \StringTok{"Tai Rui Barge, Yellow Sea"} \SpecialCharTok{|}
        \CommentTok{\# OR}
\NormalTok{      location }\SpecialCharTok{==} \StringTok{"DeBo 3 Barge, Yellow Sea"} \SpecialCharTok{\textasciitilde{}} \StringTok{"Yellow Sea"}\NormalTok{,}
\NormalTok{      location }\SpecialCharTok{==} \StringTok{"Launch Plateform, Shahrud Missile Test Site"} \SpecialCharTok{\textasciitilde{}} \StringTok{"Shahrud Missile Test Site"}\NormalTok{,}
      \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}} \FunctionTok{word}\NormalTok{(location, }\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)}
\NormalTok{    )}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\hypertarget{rechecking-the-unique-countries-list}{%
\subsubsection{Rechecking the unique countries
list}\label{rechecking-the-unique-countries-list}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(space\_missions\_transformed}\SpecialCharTok{$}\NormalTok{country)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "Kazakhstan"                "USA"                      
##  [3] "Russia"                    "France"                   
##  [5] "Japan"                     "Kenya"                    
##  [7] "Australia"                 "China"                    
##  [9] "India"                     "Israel"                   
## [11] "Canaria"                   "Brazil"                   
## [13] "Barents Sea"               "Korea"                    
## [15] "Pacific Ocean"             "Iran"                     
## [17] "Range Facility"            "Zealand"                  
## [19] "Mexico"                    "Yellow Sea"               
## [21] "Shahrud Missile Test Site"
\end{verbatim}

\hypertarget{replacing-few-of-the-country-names-further-based-on-the-location-and-rocket-information}{%
\subsubsection{Replacing few of the country names further based on the
location and rocket
information}\label{replacing-few-of-the-country-names-further-based-on-the-location-and-rocket-information}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\OtherTok{\textless{}{-}}\NormalTok{ space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{country =} \FunctionTok{str\_replace}\NormalTok{(country, }\StringTok{"Canaria"}\NormalTok{, }\AttributeTok{replacement =} \StringTok{"USA"}\NormalTok{),}
    \AttributeTok{country =} \FunctionTok{str\_replace}\NormalTok{(country, }\StringTok{"Barents Sea"}\NormalTok{, }\AttributeTok{replacement =} \StringTok{"Russia"}\NormalTok{),}
    \AttributeTok{country =} \FunctionTok{str\_replace}\NormalTok{(country, }\StringTok{"Yellow Sea"}\NormalTok{, }\AttributeTok{replacement =} \StringTok{"China"}\NormalTok{),}
    \AttributeTok{country =} \FunctionTok{str\_replace}\NormalTok{(country, }\StringTok{"Range Facility"}\NormalTok{, }\AttributeTok{replacement =} \StringTok{"USA"}\NormalTok{),}
    \AttributeTok{country =} \FunctionTok{str\_replace}\NormalTok{(country, }\StringTok{"Shahrud Missile Test Site"}\NormalTok{, }\AttributeTok{replacement =} \StringTok{"Iran"}\NormalTok{),}
    \AttributeTok{country =} \FunctionTok{str\_replace}\NormalTok{(country, }\StringTok{"Zealand"}\NormalTok{, }\AttributeTok{replacement =} \StringTok{"New Zealand"}\NormalTok{)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\hypertarget{looking-at-the-number-of-space-missions-by-country}{%
\subsubsection{Looking at the number of space missions by
country}\label{looking-at-the-number-of-space-missions-by-country}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{count}\NormalTok{(country, }\AttributeTok{sort =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          country    n
## 1            USA 1470
## 2         Russia 1419
## 3     Kazakhstan  719
## 4          China  368
## 5         France  318
## 6          Japan  130
## 7          India   82
## 8  Pacific Ocean   36
## 9    New Zealand   28
## 10          Iran   17
## 11        Israel   11
## 12         Korea   10
## 13         Kenya    9
## 14     Australia    6
## 15        Mexico    4
## 16        Brazil    3
\end{verbatim}

\hypertarget{data-analysis-and-visualizations}{%
\section{Data Analysis And
Visualizations}\label{data-analysis-and-visualizations}}

In this phase, I will analyze the data to answer the questions and
create plots using ggplot2 library of the tidyverse to show the trends
in the data.

\hypertarget{which-countries-have-had-the-most-successful-space-missions-has-it-always-been-that-way}{%
\subsection{\texorpdfstring{\textbf{Which countries have had the most
successful space missions? Has it always been that
way?}}{Which countries have had the most successful space missions? Has it always been that way?}}\label{which-countries-have-had-the-most-successful-space-missions-has-it-always-been-that-way}}

\hypertarget{finding-the-countries-with-the-most-successful-space-missions}{%
\subsubsection{Finding the countries with the most successful space
missions}\label{finding-the-countries-with-the-most-successful-space-missions}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(mission\_status }\SpecialCharTok{==} \StringTok{"Success"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{count}\NormalTok{(country, }\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##          country    n
## 1         Russia 1325
## 2            USA 1300
## 3     Kazakhstan  625
## 4          China  338
## 5         France  299
## 6          Japan  117
## 7          India   68
## 8  Pacific Ocean   33
## 9    New Zealand   25
## 10        Israel    9
## 11         Kenya    9
## 12          Iran    7
## 13         Korea    4
## 14     Australia    3
\end{verbatim}

\hypertarget{plotting-the-countries-with-the-number-of-successful-missions}{%
\subsubsection{Plotting the countries with the number of successful
missions}\label{plotting-the-countries-with-the-number-of-successful-missions}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(mission\_status }\SpecialCharTok{==} \StringTok{"Success"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(country) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{count =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(count)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{fct\_reorder}\NormalTok{(country, }\SpecialCharTok{{-}}\NormalTok{count), }\AttributeTok{y=}\NormalTok{ count))}\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =}\NormalTok{ count), }\AttributeTok{vjust =} \SpecialCharTok{{-}}\FloatTok{0.2}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Countries With Successful Space Missions"}\NormalTok{,}
       \AttributeTok{x=} \StringTok{"Country Name"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Number of successful launches"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{60}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Rmarkdown_space_missions_analysis_files/figure-latex/plot successful countries missions-1.pdf}

\hypertarget{table-of-missions-and-their-status-per-country}{%
\subsubsection{Table of missions and their status per
country}\label{table-of-missions-and-their-status-per-country}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{table}\NormalTok{(space\_missions\_transformed}\SpecialCharTok{$}\NormalTok{country,space\_missions\_transformed}\SpecialCharTok{$}\NormalTok{mission\_status)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                
##                 Failure Partial Failure Prelaunch Failure Success
##   Australia           3               0                 0       3
##   Brazil              2               0                 1       0
##   China              24               6                 0     338
##   France             14               5                 0     299
##   India               9               5                 0      68
##   Iran                9               0                 1       7
##   Israel              2               0                 0       9
##   Japan              10               3                 0     117
##   Kazakhstan         72              21                 1     625
##   Kenya               0               0                 0       9
##   Korea               6               0                 0       4
##   Mexico              1               3                 0       0
##   New Zealand         3               0                 0      25
##   Pacific Ocean       3               0                 0      33
##   Russia             64              30                 0    1325
##   USA               135              34                 1    1300
\end{verbatim}

\hypertarget{plotting-mission-status-distribution-over-the-total-missions-completed-by-top-5-countries}{%
\subsubsection{Plotting mission status distribution over the total
missions completed by top 5
countries}\label{plotting-mission-status-distribution-over-the-total-missions-completed-by-top-5-countries}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(country }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"USA"}\NormalTok{, }\StringTok{"Russia"}\NormalTok{, }\StringTok{"Kazakhstan"}\NormalTok{, }\StringTok{"China"}\NormalTok{, }\StringTok{"France"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(country,mission\_status) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{count =} \FunctionTok{n}\NormalTok{())}\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_max}\NormalTok{(count, }\AttributeTok{n =} \DecValTok{5}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{fct\_reorder}\NormalTok{(country, }\SpecialCharTok{{-}}\NormalTok{count), }\AttributeTok{y =}\NormalTok{ count, }\AttributeTok{fill =}\NormalTok{ mission\_status)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Mission Status of Space launches"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Country"}\NormalTok{,}
       \AttributeTok{y =} \StringTok{"Number of launches"}\NormalTok{) }
\end{Highlighting}
\end{Shaded}

\includegraphics{Rmarkdown_space_missions_analysis_files/figure-latex/plot mission status of top 5 countries-1.pdf}

\hypertarget{how-have-rocket-launches-trended-across-time-has-mission-success-rate-increased}{%
\subsection{\texorpdfstring{\textbf{How have rocket launches trended
across time? Has mission success rate
increased?}}{How have rocket launches trended across time? Has mission success rate increased?}}\label{how-have-rocket-launches-trended-across-time-has-mission-success-rate-increased}}

\hypertarget{plotting-the-total-rocket-launches-from-1957--2022.}{%
\subsubsection{Plotting the total rocket launches from 1957-
2022.}\label{plotting-the-total-rocket-launches-from-1957--2022.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(year) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{count =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ year, }\AttributeTok{y =}\NormalTok{ count)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =} \StringTok{"indianred3"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"indianred3"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Launch Year"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Number of Rocket Launches"}\NormalTok{, }
       \AttributeTok{title =} \StringTok{"Rocket Launches across time"}\NormalTok{,}
       \AttributeTok{subtitle =} \StringTok{"1957 to 2022"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{,}
        \AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{caption =} \StringTok{"Data Source: Maven Analytics: Space Missions Dataset"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula = 'y ~ x'
\end{verbatim}

\includegraphics{Rmarkdown_space_missions_analysis_files/figure-latex/plot rocket launches over time-1.pdf}

Here, We can see the trend in the number of space missions which
increased from 1957-1975, decreased gradually from 1975-2005 and
increased again from 2005 to 2022.

\hypertarget{plotting-successful-launches-of-russia-and-usa-from-1957-2022.}{%
\subsubsection{Plotting successful launches of Russia and USA from
1957-2022.}\label{plotting-successful-launches-of-russia-and-usa-from-1957-2022.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(mission\_status }\SpecialCharTok{==} \StringTok{"Success"} \SpecialCharTok{\&}\NormalTok{ country }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Russia"}\NormalTok{, }\StringTok{"USA"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(country,year) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{count =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ year, }\AttributeTok{y =}\NormalTok{ count, }\AttributeTok{color =}\NormalTok{ country)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{scale\_color\_manual}\NormalTok{(}\AttributeTok{name =} \StringTok{"Country"}\NormalTok{,}
                     \AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"darkgreen"}\NormalTok{,}\StringTok{"indianred3"}\NormalTok{))}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Launch Year"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Number of Rocket Launches"}\NormalTok{, }
       \AttributeTok{title =} \StringTok{"Successful Rocket Launches of Russia and USA"}\NormalTok{,}
       \AttributeTok{subtitle =} \StringTok{"1957 to 2022"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"right"}\NormalTok{,}
        \AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{caption =} \StringTok{"Data Source: Maven Analytics: Space Missions Dataset"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Rmarkdown_space_missions_analysis_files/figure-latex/Russia and USA missions over time-1.pdf}

Here we can see a pattern across time in the launches by both USA and
Russia having relatively closer number of total successful launches.

We can see that Russia had higher number of successful launches than USA
from 1968 to 1990 but the trend changes later from 1990 to 2022 where
USA had a higher number of successful launches than Russia.

\hypertarget{finding-average-mission-success-rate-over-time}{%
\subsubsection{Finding average mission success rate over
time}\label{finding-average-mission-success-rate-over-time}}

\hypertarget{first-creating-a-new-data-frame-to-look-at-the-number-and-status-of-mission-launches-by-country-and-year}{%
\paragraph{First creating a new data frame to look at the number and
status of mission launches by country and
year}\label{first-creating-a-new-data-frame-to-look-at-the-number-and-status-of-mission-launches-by-country-and-year}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mission\_status }\OtherTok{\textless{}{-}}\NormalTok{ space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(country, year, mission\_status) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{count =} \FunctionTok{n}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\hypertarget{reshaping-the-above-data-from-long-to-wide-format}{%
\paragraph{Reshaping the above data from long to wide
format}\label{reshaping-the-above-data-from-long-to-wide-format}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mission\_status }\OtherTok{\textless{}{-}}\NormalTok{ mission\_status }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}\AttributeTok{names\_from =}\NormalTok{ mission\_status,}\AttributeTok{values\_from =}\NormalTok{ count)}
\end{Highlighting}
\end{Shaded}

\hypertarget{replacing-0-with-na-values}{%
\paragraph{Replacing 0 with NA
values}\label{replacing-0-with-na-values}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mission\_status }\OtherTok{\textless{}{-}}\NormalTok{ mission\_status }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{replace\_na}\NormalTok{(}\FunctionTok{list}\NormalTok{(}\StringTok{"Success"} \OtherTok{=} \DecValTok{0}\NormalTok{, }\StringTok{"Failure"} \OtherTok{=} \DecValTok{0}\NormalTok{, }\StringTok{"Prelaunch Failure"} \OtherTok{=} \DecValTok{0}\NormalTok{, }\StringTok{"Partial Failure"} \OtherTok{=} \DecValTok{0}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\hypertarget{changing-the-variable-names-for-better-readability}{%
\paragraph{Changing the variable names for better
readability}\label{changing-the-variable-names-for-better-readability}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colnames}\NormalTok{(mission\_status)}\OtherTok{\textless{}{-}} \FunctionTok{tolower}\NormalTok{(}\FunctionTok{colnames}\NormalTok{(mission\_status)) }

\FunctionTok{colnames}\NormalTok{(mission\_status) }\OtherTok{\textless{}{-}}  \FunctionTok{gsub}\NormalTok{(}\StringTok{"prelaunch failure"}\NormalTok{, }\StringTok{"prelaunch\_failure"}\NormalTok{,}
       \FunctionTok{gsub}\NormalTok{(}\StringTok{"partial failure"}\NormalTok{, }\StringTok{"partial\_failure"}\NormalTok{,}
            \FunctionTok{colnames}\NormalTok{(mission\_status)))}
\end{Highlighting}
\end{Shaded}

\hypertarget{adding-the-column-of-success-rate}{%
\paragraph{Adding the column of success
rate}\label{adding-the-column-of-success-rate}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mission\_status }\OtherTok{\textless{}{-}}\NormalTok{ mission\_status }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{success\_rate =}\NormalTok{ (success}\SpecialCharTok{/}\FunctionTok{sum}\NormalTok{(success, failure, prelaunch\_failure, partial\_failure)) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{plot-average-success-rate-of-the-total-missions-from-1957-2022}{%
\subsubsection{Plot average success rate of the total missions from
1957-2022}\label{plot-average-success-rate-of-the-total-missions-from-1957-2022}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mission\_status }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{group\_by}\NormalTok{(year) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{mean\_success\_rate =} \FunctionTok{mean}\NormalTok{(success\_rate)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ year, }\AttributeTok{y =}\NormalTok{ mean\_success\_rate)) }\SpecialCharTok{+}
  \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{color =} \StringTok{"indianred3"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{color =} \StringTok{"indianred3"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Launch Year"}\NormalTok{, }
       \AttributeTok{y =} \StringTok{"Average Success Rate"}\NormalTok{, }
       \AttributeTok{title =} \StringTok{"Success Rate Over Time"}\NormalTok{,}
       \AttributeTok{subtitle =} \StringTok{"1957 to 2022"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{,}
        \AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{90}\NormalTok{, }\AttributeTok{vjust =} \FloatTok{0.5}\NormalTok{, }\AttributeTok{hjust =} \FloatTok{0.5}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{caption =} \StringTok{"Data Source: Maven Analytics: Space Missions Dataset"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using method = 'loess' and formula = 'y ~ x'
\end{verbatim}

\includegraphics{Rmarkdown_space_missions_analysis_files/figure-latex/plot avg success rate over time-1.pdf}

We can see in the above graph that the average success rate of all the
missions increases from 1957- 1980 but stays more or less the same from
1980- 2022.

\hypertarget{which-rocket-has-been-used-for-the-most-space-missions-is-it-still-active}{%
\subsection{\texorpdfstring{\textbf{Which rocket has been used for the
most space missions? Is it still
active?}}{Which rocket has been used for the most space missions? Is it still active?}}\label{which-rocket-has-been-used-for-the-most-space-missions-is-it-still-active}}

\hypertarget{looking-at-the-rockets-used-by-all-the-countries-for-space-missions}{%
\subsubsection{Looking at the rockets used by all the countries for
space
missions}\label{looking-at-the-rockets-used-by-all-the-countries-for-space-missions}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{count}\NormalTok{(country, rocket, rocket\_status, }\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(n))}
\end{Highlighting}
\end{Shaded}

\hypertarget{creating-a-function-to-look-at-individual-country-rockets-for-automating-the-process}{%
\paragraph{Creating a function to look at individual country rockets for
automating the
process}\label{creating-a-function-to-look-at-individual-country-rockets-for-automating-the-process}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rockets\_by\_country }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(country\_name)\{}
\NormalTok{  space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(country }\SpecialCharTok{==}\NormalTok{ country\_name) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{count}\NormalTok{(rocket, rocket\_status, }\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(n))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\hypertarget{looking-at-rockets-used-by-top-5-countries-for-the-missions}{%
\paragraph{Looking at rockets used by top 5 countries for the
missions}\label{looking-at-rockets-used-by-top-5-countries-for-the-missions}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{rockets\_by\_country}\NormalTok{(}\StringTok{"Russia"}\NormalTok{)}

\FunctionTok{rockets\_by\_country}\NormalTok{(}\StringTok{"USA"}\NormalTok{)}

\FunctionTok{rockets\_by\_country}\NormalTok{(}\StringTok{"Kazakhstan"}\NormalTok{)}

\FunctionTok{rockets\_by\_country}\NormalTok{(}\StringTok{"China"}\NormalTok{)}

\FunctionTok{rockets\_by\_country}\NormalTok{(}\StringTok{"France"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{creating-a-new-data-frame-for-the-top-5-rockets-used-by-each-of-the-top-5-countries}{%
\paragraph{Creating a new data frame for the top 5 rockets used by each
of the top 5
countries}\label{creating-a-new-data-frame-for-the-top-5-rockets-used-by-each-of-the-top-5-countries}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{top\_five\_rockets }\OtherTok{\textless{}{-}}\NormalTok{ space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(country }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Russia"}\NormalTok{, }\StringTok{"USA"}\NormalTok{, }\StringTok{"Kazakhstan"}\NormalTok{, }\StringTok{"China"}\NormalTok{, }\StringTok{"France"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(country, rocket) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{launch\_count =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{slice\_max}\NormalTok{(launch\_count, }\AttributeTok{n =} \DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{plotting-top-5-rockets-used-for-space-missions-by-the-above-countries}{%
\subsubsection{Plotting top 5 rockets used for space missions by the
above
countries}\label{plotting-top-5-rockets-used-for-space-missions-by-the-above-countries}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(country }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Russia"}\NormalTok{, }\StringTok{"USA"}\NormalTok{, }\StringTok{"Kazakhstan"}\NormalTok{, }\StringTok{"China"}\NormalTok{, }\StringTok{"France"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(country, rocket) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{cnt =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{slice\_max}\NormalTok{(cnt, }\AttributeTok{n =} \DecValTok{5}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(rocket, }\SpecialCharTok{{-}}\NormalTok{cnt), }\AttributeTok{y =}\NormalTok{ cnt)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =}\NormalTok{ cnt), }\AttributeTok{vjust =} \SpecialCharTok{{-}}\FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{country, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{, }\AttributeTok{scales =} \StringTok{"free\_x"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Rockets"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Number of launches"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Rmarkdown_space_missions_analysis_files/figure-latex/plot top 5 rockets for top 5 countries-1.pdf}

\hypertarget{creating-a-function-to-plot-top-5-rockets-of-a-country-to-automate-the-process}{%
\paragraph{Creating a function to plot top 5 rockets of a country to
automate the
process}\label{creating-a-function-to-plot-top-5-rockets-of-a-country-to-automate-the-process}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot\_top\_five\_rockets }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(country\_name)\{}
\NormalTok{  space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(country }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(country\_name)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(country, rocket) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{cnt =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{slice\_max}\NormalTok{(cnt, }\AttributeTok{n =} \DecValTok{5}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(rocket, }\SpecialCharTok{{-}}\NormalTok{cnt), }\AttributeTok{y =}\NormalTok{ cnt)) }\SpecialCharTok{+}
    \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =}\NormalTok{ cnt), }\AttributeTok{vjust =} \SpecialCharTok{{-}}\FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{country, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{, }\AttributeTok{scales =} \StringTok{"free\_x"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Rockets"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Number of launches"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\hypertarget{plotting-top-5-rockets-used-by-each-of-the-top-5-countries}{%
\paragraph{Plotting top 5 rockets used by each of the top 5
countries}\label{plotting-top-5-rockets-used-by-each-of-the-top-5-countries}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_top\_five\_rockets}\NormalTok{(}\StringTok{"Russia"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Rmarkdown_space_missions_analysis_files/figure-latex/plotting each country top 5 rockets-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_top\_five\_rockets}\NormalTok{(}\StringTok{"USA"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Rmarkdown_space_missions_analysis_files/figure-latex/plotting each country top 5 rockets-2.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_top\_five\_rockets}\NormalTok{(}\StringTok{"Kazakhstan"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Rmarkdown_space_missions_analysis_files/figure-latex/plotting each country top 5 rockets-3.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_top\_five\_rockets}\NormalTok{(}\StringTok{"China"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Rmarkdown_space_missions_analysis_files/figure-latex/plotting each country top 5 rockets-4.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_top\_five\_rockets}\NormalTok{(}\StringTok{"France"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Rmarkdown_space_missions_analysis_files/figure-latex/plotting each country top 5 rockets-5.pdf}

\hypertarget{determining-status-of-the-above-rockets}{%
\subsubsection{Determining status of the above
rockets}\label{determining-status-of-the-above-rockets}}

\hypertarget{creating-a-function-to-plot-rocket-status-of-top-5-rockets-of-each-of-the-countries}{%
\paragraph{Creating a function to plot rocket status of top 5 rockets of
each of the
countries}\label{creating-a-function-to-plot-rocket-status-of-top-5-rockets-of-each-of-the-countries}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot\_rocket\_status }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(country\_name, rocket\_name1, rocket\_name2, rocket\_name3,rocket\_name4, rocket\_name5)\{}
\NormalTok{  space\_missions\_transformed }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(country }\SpecialCharTok{==}\NormalTok{ country\_name }\SpecialCharTok{\&}\NormalTok{ rocket }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(rocket\_name1,rocket\_name2, rocket\_name3, rocket\_name4, rocket\_name5)) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{group\_by}\NormalTok{(rocket, rocket\_status) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{cnt =} \FunctionTok{n}\NormalTok{()) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{slice\_max}\NormalTok{(cnt, }\AttributeTok{n =} \DecValTok{5}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(rocket, }\SpecialCharTok{{-}}\NormalTok{cnt), }\AttributeTok{y =}\NormalTok{ cnt, }\AttributeTok{fill =}\NormalTok{ rocket\_status)) }\SpecialCharTok{+}
    \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Active"} \OtherTok{=} \StringTok{"darkgreen"}\NormalTok{, }\StringTok{"Retired"} \OtherTok{=} \StringTok{"indianred3"}\NormalTok{))}\SpecialCharTok{+}
    \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =}\NormalTok{ cnt), }\AttributeTok{vjust =} \SpecialCharTok{{-}}\FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{))}\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =}  \StringTok{"Top 5 Rocket Launches"}\NormalTok{,}
      \AttributeTok{subtitle =}\NormalTok{ country\_name,}
      \AttributeTok{x =} \StringTok{"Rockets"}\NormalTok{, }
      \AttributeTok{y =} \StringTok{"Number of launches"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\hypertarget{plotting-top-5-russian-rockets-and-their-status}{%
\subsubsection{Plotting top 5 Russian rockets and their
status}\label{plotting-top-5-russian-rockets-and-their-status}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot\_rocket\_status}\NormalTok{(}\StringTok{"Russia"}\NormalTok{,}\StringTok{"Cosmos{-}3M (11K65M)"}\NormalTok{,}\StringTok{"Voskhod"}\NormalTok{, }\StringTok{"Cosmos{-}2I (63SM)"}\NormalTok{, }\StringTok{"Tsyklon{-}3"}\NormalTok{, }\StringTok{"Molniya{-}M /Block ML"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Rmarkdown_space_missions_analysis_files/figure-latex/status of Russia rockets-1.pdf}

We can see that the rocket which is mostly used for most space missions
is \textbf{Cosmos-3M (11K65M)} of Russia and it is \textbf{Retired}.

\hypertarget{conclusion}{%
\section{Conclusion}\label{conclusion}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Russia, USA, Kazakhstan, China and France are the top 5 countries
  which had the most successful space missions.
\item
  Russia and USA had relatively higher number of successful rocket
  launches than the other countries.
\item
  Russia had higher number of successful launches than USA from 1968 to
  1990 but the trend changes later from 1990 to 2022 where USA had more
  successful launches than Russia.
\item
  There is an interesting trend in the total space missions from 1957-
  2022 where total number of space missions increased and decreased over
  time as seen from the line chart.
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\alph{enumi}.}
\item
  Increased from 1957- 1975 : Mainly due to space race between USA and
  Soviet Union with rise in increased federal support and funding
  resulting in increased launches during that time frame. The race
  however ended in 1975 with the first cooperative launch of
  Apollo-Soyuz mission. \footnote{Muir-Harmony, T. (2017, February 27).
    The Space Race and American Foreign Relations. Oxford Research
    Encyclopedia of American History. Retrieved 8 Aug.~2023, from
    \url{https://oxfordre.com/americanhistory/view/10.1093/acrefore/9780199329175.001.0001/acrefore-9780199329175-e-274}.}
\item
  Decreased from 1975- 2005 : Possibly due increased cost of launching
  big satellites making space missions very costly. In addition to the
  increased cost, there was reduction in federal space funding to NASA
  after the space race which further slowed the space mission launches.
  \footnote{Seck, N. (2012, August 26). Space race, on a budget, was not
    how Armstrong saw it. Phys.org.
    \url{https://phys.org/news/2012-08-space-armstrong.html}}
\item
  Increased from 2005- 2022 : Due to increased commercialization,
  technological advancements and building of smaller space crafts with
  missions becoming cost and fuel efficient. This helped more countries
  initiate their space missions.\footnote{Louise Fox, L. S., West, D.
    M., Onder, H., \& Katharine Kelley, J. B. (2023, June 24). How space
    exploration is fueling the Fourth Industrial Revolution. Brookings.
    \url{https://www.brookings.edu/articles/how-space-exploration-is-fueling-the-fourth-industrial-revolution/}}
\end{enumerate}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\item
  The average mission success rate increased with the start of the
  launches in 1957 and until 1980 due to space race between Soviet Union
  and USA as described above but then has been steady in the later
  years.
\item
  The rocket used for the most space missions is Cosmos-3M (11K65M) of
  Russia and it is Retired.
\end{enumerate}

\hypertarget{thank-you-for-taking-the-time-to-go-through-my-analysis-process-and-would-appreciate-any-valuable-feedback-to-improve-my-learning.}{%
\subparagraph{\texorpdfstring{\textbf{Thank you for taking the time to
go through my analysis process and would appreciate any valuable
feedback to improve my
learning.}}{Thank you for taking the time to go through my analysis process and would appreciate any valuable feedback to improve my learning.}}\label{thank-you-for-taking-the-time-to-go-through-my-analysis-process-and-would-appreciate-any-valuable-feedback-to-improve-my-learning.}}

\hypertarget{references}{%
\subsubsection{References}\label{references}}

\href{https://mavenanalytics.io/data-playground?page=2\&pageSize=5}{Maven
Analytics Dataset}

\end{document}
